#  Copyright (c) 2019.
#  Ahmad Syafiq Kamil

# Generated by Django 2.2.7 on 2019-12-02 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dokumen.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nomor_surat_lengkap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor Surat Lengkap')),
                ('nomor_surat', models.IntegerField(verbose_name='Nomor Surat')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('pejabat_penandatangan', models.CharField(max_length=255, verbose_name='Pejabat Penandatangan')),
                ('perihal', models.TextField(blank=True, null=True, verbose_name='Perihal')),
                ('file_dokumen', models.FileField(upload_to='document/%Y-%m-%d/', validators=[dokumen.validators.validate_file_extension])),
                ('status', models.CharField(choices=[('0', 'BELUM DIPROSES'), ('1', 'PROSES'), ('2', 'DISPOSISI'), ('3', 'BATAL')], default=0, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tbl_dokumen',
            },
        ),
        migrations.CreateModel(
            name='Fungsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, verbose_name='Kode Fungsi')),
                ('fungsi', models.CharField(max_length=100, verbose_name='Fungsi / Bidang Teknis')),
                ('koordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koordinator', to=settings.AUTH_USER_MODEL, verbose_name='Koordinator Fungsi')),
            ],
            options={
                'db_table': 'tbl_fungsi',
            },
        ),
        migrations.CreateModel(
            name='JenisDokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, verbose_name='Kode Dokumen')),
                ('jenis_dokumen', models.CharField(max_length=255, verbose_name='Jenis Dokumen')),
            ],
            options={
                'db_table': 'tbl_jenis_dokumen',
            },
        ),
        migrations.CreateModel(
            name='Klasifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=5, verbose_name='Kode Klasifikasi')),
                ('nama_klasifikasi', models.CharField(max_length=100, verbose_name='Nama Klasifikasi')),
            ],
            options={
                'db_table': 'tbl_klasifikasi',
            },
        ),
        migrations.CreateModel(
            name='TujuanDokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Status')),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.Dokumen')),
                ('fungsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.Fungsi')),
            ],
            options={
                'db_table': 'tbl_tujuan_dokumen',
            },
        ),
        migrations.AddField(
            model_name='dokumen',
            name='fungsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungsi_pengirim', to='dokumen.Fungsi', verbose_name='Fungsi'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='jenis_dokumen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenis', to='dokumen.JenisDokumen', verbose_name='Jenis Dokumen'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='klasifikasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasifikasi_dokumen', to='dokumen.Klasifikasi', verbose_name='Tujuan Dokumen'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='tujuan',
            field=models.ManyToManyField(through='dokumen.TujuanDokumen', to='dokumen.Fungsi'),
        ),
        migrations.AddField(
            model_name='dokumen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pengirim', to=settings.AUTH_USER_MODEL, verbose_name='Pengirim'),
        ),
    ]
