# Generated by Django 2.2.7 on 2019-11-12 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisDokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, verbose_name='Kode Dokumen')),
                ('jenis_dokumen', models.CharField(max_length=255, verbose_name='Jenis Dokumen')),
            ],
            options={
                'db_table': 'tbl_jenis_dokumen',
            },
        ),
        migrations.CreateModel(
            name='Klasifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=5, verbose_name='Kode Klasifikasi')),
                ('nama_klasifikasi', models.CharField(max_length=100, verbose_name='Nama Klasifikasi')),
            ],
            options={
                'db_table': 'tbl_klasifikasi',
            },
        ),
        migrations.CreateModel(
            name='Fungsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, verbose_name='Kode Fungsi')),
                ('fungsi', models.CharField(max_length=100, verbose_name='Fungsi / Bidang Teknis')),
                ('koordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koordinator', to=settings.AUTH_USER_MODEL, verbose_name='Koordinator Fungsi')),
            ],
            options={
                'db_table': 'tbl_fungsi',
            },
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nomor_surat_lengkap', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor Surat Lengkap')),
                ('nomor_surat', models.IntegerField(verbose_name='Nomor Surat')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('pejabat_penandatangan', models.CharField(max_length=255, verbose_name='Pejabat Penandatangan')),
                ('perihal', models.TextField(blank=True, null=True, verbose_name='Perihal')),
                ('file_dokumen', models.FileField(upload_to='document/%Y-%m-%d/')),
                ('fungsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungsi_pengirim', to='dokumen.Fungsi', verbose_name='Fungsi')),
                ('jenis_dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenis', to='dokumen.JenisDokumen', verbose_name='Jenis Dokumen')),
                ('klasifikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasifikasi_dokumen', to='dokumen.Klasifikasi', verbose_name='Tujuan Dokumen')),
                ('tujuan', models.ManyToManyField(to='dokumen.Fungsi', verbose_name='Tujuan Dokumen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pengirim', to=settings.AUTH_USER_MODEL, verbose_name='Pengirim')),
            ],
            options={
                'db_table': 'tbl_dokumen',
            },
        ),
    ]
