# Generated by Django 2.2.7 on 2019-11-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan'),
        ),
    ]
