# Generated by Django 2.2.6 on 2019-11-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='file_dokumen',
            field=models.FileField(upload_to='document/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='nomor_surat',
            field=models.IntegerField(verbose_name='Nomor Surat'),
        ),
    ]
