#  Copyright (c) 2019.
#  Ahmad Syafiq Kamil

# Generated by Django 2.2.7 on 2019-12-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='tujuan',
            field=models.ManyToManyField(related_name='tujuan_dokumen', through='dokumen.TujuanDokumen', to='dokumen.Fungsi'),
        ),
    ]
