# Generated by Django 2.2.7 on 2019-11-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_auto_20191105_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='tujuan',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='tujuan',
            field=models.ManyToManyField(related_name='tujuan', to='dokumen.Fungsi', verbose_name='Tujuan Dokumen'),
        ),
    ]
