# Generated by Django 2.2.7 on 2019-11-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_dokumen_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='status',
            field=models.CharField(choices=[('0', 'BELUM DIPROSES'), ('1', 'PROSES'), ('2', 'DISPOSISI'), ('3', 'BATAL')], default=0, max_length=10, null=True),
        ),
    ]
