# Generated by Django 2.2.7 on 2019-11-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0003_auto_20191112_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='tujuan',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='tujuan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tujuan', to='dokumen.Fungsi', verbose_name='Tujuan Dokumen'),
            preserve_default=False,
        ),
    ]
