# Generated by Django 2.2.7 on 2019-11-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0004_auto_20191112_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='tujuan',
        ),
        migrations.AddField(
            model_name='dokumen',
            name='tujuan',
            field=models.ManyToManyField(related_name='tujuan', to='dokumen.Fungsi', verbose_name='Tujuan Dokumen'),
        ),
    ]
