# Generated by Django 2.2.7 on 2019-12-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0004_auto_20191210_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='tujuan_eksternal',
            field=models.TextField(blank=True, null=True, verbose_name='Tujuan Eksternal'),
        ),
    ]
