# Generated by Django 2.2.7 on 2019-11-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0005_auto_20191112_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='tujuan',
            field=models.ManyToManyField(to='dokumen.Fungsi', verbose_name='Tujuan Dokumen'),
        ),
    ]
