# Generated by Django 2.2.7 on 2020-01-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0006_auto_20191230_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='nomor_surat_back',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Nomor Backdate'),
        ),
    ]
