# Generated by Django 2.2.7 on 2020-01-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0007_dokumen_nomor_surat_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='nomor_surat_back',
        ),
    ]
