# Generated by Django 2.2.7 on 2020-01-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0008_remove_dokumen_nomor_surat_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='isi_dokumen',
            field=models.TextField(blank=True, null=True, verbose_name='Isi Dokumen'),
        ),
    ]
