# Generated by Django 2.2.7 on 2020-01-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0009_dokumen_isi_dokumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='status',
        ),
    ]
