# Generated by Django 2.2.7 on 2020-01-17 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0010_remove_dokumen_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungsi',
            name='koordinator',
        ),
    ]
