# Generated by Django 2.2.7 on 2020-01-17 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokumen', '0011_remove_fungsi_koordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='status',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ValidasiDokumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.Dokumen')),
                ('penandatangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
