# Generated by Django 2.2.7 on 2020-01-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0012_auto_20200117_1437'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='validasidokumen',
            table='tbl_validasi_dokumen',
        ),
    ]
