# Generated by Django 2.2.6 on 2019-10-31 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Alamat Email')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='Nama Anggota')),
                ('active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('staff', models.BooleanField(default=False, verbose_name='Status Manajer Proyek')),
                ('surveyor', models.BooleanField(default=False, verbose_name='Status Surveyor')),
                ('analis', models.BooleanField(default=False, verbose_name='Status Analis')),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LoggedInUser',
            },
        ),
    ]
