# Generated by Django 2.2.6 on 2019-10-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='analis',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surveyor',
        ),
        migrations.AddField(
            model_name='user',
            name='fungsi_kode',
            field=models.CharField(blank=True, max_length=2, verbose_name='Nama Lengkap'),
        ),
        migrations.AddField(
            model_name='user',
            name='koordinator_fungsi',
            field=models.CharField(blank=True, max_length=2, verbose_name='Koordinator Fungsi'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_foto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Foto Pengguna'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_menerima_disposisi',
            field=models.CharField(blank=True, max_length=2, verbose_name='Dapat Menerima Disposisi'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_nama_lengkap',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Lengkap'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_notifikasi_email',
            field=models.CharField(blank=True, max_length=2, verbose_name='Email Notifikasi'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, max_length=2, verbose_name='Status Pengguna'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Pengguna'),
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
