# Generated by Django 2.2.7 on 2019-12-02 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokumen', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='fungsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungsi_user', to='dokumen.Fungsi'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
