# Generated by Django 2.2.7 on 2020-01-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191202_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_dokumen',
            field=models.BooleanField(default=False),
        ),
    ]
