# Generated by Django 2.2.7 on 2019-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191112_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_nama_lengkap',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='user_nama_lengkap',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama Lengkap'),
        ),
    ]
