# Generated by Django 2.2.7 on 2020-01-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0008_remove_dokumen_nomor_surat_back'),
        ('accounts', '0003_user_staff_dokumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fungsi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fungsi_pengguna', to='dokumen.Fungsi'),
            preserve_default=False,
        ),
    ]
