# Generated by Django 2.2.7 on 2019-11-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191112_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kode_jabatan', to='accounts.Jabatan'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='user_foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_picture'),
        ),
    ]
