# Generated by Django 2.2.6 on 2019-10-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fungsi_kode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='koordinator_fungsi',
        ),
    ]
