# Generated by Django 2.2.6 on 2019-10-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191031_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_menerima_disposisi',
        ),
    ]
