# Generated by Django 2.2.7 on 2020-01-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_korfung'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jabatan',
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
