# Generated by Django 2.2.6 on 2019-10-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_user_menerima_disposisi'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tbl_User',
        ),
    ]
