# Generated by Django 2.2.7 on 2020-01-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200117_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='korfung',
        ),
    ]
