# Generated by Django 2.2.7 on 2020-01-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_korfung'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='korfung',
            field=models.BooleanField(default=False),
        ),
    ]
