# Generated by Django 2.2.6 on 2019-11-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fungsi_kode',
            field=models.CharField(blank=True, max_length=2, verbose_name='Kode Fungsi'),
        ),
    ]
