# Generated by Django 2.2.6 on 2019-11-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_fungsi_kode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fungsi_kode',
        ),
    ]
