# Generated by Django 2.2.7 on 2019-11-11 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_fungsi_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=2, verbose_name='Kode Jabatan')),
                ('jabatan', models.CharField(max_length=255, verbose_name='Jabatan')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_foto',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_notifikasi_email',
        ),
        migrations.CreateModel(
            name='Profle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_foto', models.ImageField(upload_to='images/profile_picture')),
                ('user_notifikasi_email', models.CharField(blank=True, max_length=2, verbose_name='Email Notifikasi')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_jabatan', to='accounts.Jabatan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataUser_HS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, verbose_name='NIP')),
                ('pangkat', models.CharField(max_length=255, verbose_name='Pangkat/Golongan')),
                ('tmt', models.DateField(blank=True, null=True, verbose_name='TMT')),
                ('gelar_diplomatik', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gelar Diplomatik')),
                ('tmt_gelar', models.DateField(blank=True, null=True, verbose_name='TMT')),
                ('bulan_tiba', models.DateField(verbose_name='Bulan tiba di Perwakilan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestaff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pekerjaan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jenis Pekerjaan')),
                ('awal_kontrak', models.DateField(verbose_name='Awal Kontrak')),
                ('akhir_kontrak', models.DateField(verbose_name='Akhir Kontrak')),
                ('kewarganegaraan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kewarganegaraan')),
                ('pendidikan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pendidikan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datauser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
