# Generated by Django 2.2.7 on 2019-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191111_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser_hs',
            name='user',
        ),
        migrations.AddField(
            model_name='profle',
            name='akhir_kontrak',
            field=models.DateField(blank=True, null=True, verbose_name='Akhir Kontrak'),
        ),
        migrations.AddField(
            model_name='profle',
            name='awal_kontrak',
            field=models.DateField(blank=True, null=True, verbose_name='Awal Kontrak'),
        ),
        migrations.AddField(
            model_name='profle',
            name='bulan_tiba',
            field=models.DateField(blank=True, null=True, verbose_name='Bulan tiba di Perwakilan'),
        ),
        migrations.AddField(
            model_name='profle',
            name='gelar_diplomatik',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gelar Diplomatik'),
        ),
        migrations.AddField(
            model_name='profle',
            name='jenis_pekerjaan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jenis Pekerjaan'),
        ),
        migrations.AddField(
            model_name='profle',
            name='kewarganegaraan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kewarganegaraan'),
        ),
        migrations.AddField(
            model_name='profle',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='profle',
            name='pangkat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pangkat/Golongan'),
        ),
        migrations.AddField(
            model_name='profle',
            name='pendidikan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pendidikan'),
        ),
        migrations.AddField(
            model_name='profle',
            name='tmt',
            field=models.DateField(blank=True, null=True, verbose_name='TMT'),
        ),
        migrations.AddField(
            model_name='profle',
            name='tmt_gelar',
            field=models.DateField(blank=True, null=True, verbose_name='TMT'),
        ),
        migrations.DeleteModel(
            name='DataUser',
        ),
        migrations.DeleteModel(
            name='DataUser_HS',
        ),
    ]
